openapi: "3.0.0"
info:
  title: TT-Blog
  version: 1.0.0
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        image:
          type: string
          nullable: true
        bio:
          type: string
          nullable: true
    PartialPost:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        thumbnail:
          type: string
          nullable: true
        created_at:
          type: string
        updated_at:
          type: string
        is_private:
          type: boolean
    Post:
      allOf:
        - $ref: '#components/schemas/PartialPost'
        - properties:
            content:
              type: string
            authors:
              type: array
              items:
                $ref: '#/components/schemas/User'
    Tag:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
paths:
  /posts:
    get:
      description: 'ブログ記事を全て取得'
      responses:
        '200':
          description: ブログ記事が正常にレスポンスとして返されたとき
  