name: CI

on:
  push:
    branches:
      - 'main'
    paths:
      - 'web/**'
  pull_request:

defaults:
  run:
    working-directory: ./web

jobs:
  packages:
    name: check npm install
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          # defaults.run.working-directoryからではなく, ルートディレクトリからの相対パスを指定する
          node-version-file: web/.tool-versions
      - name: check npm ci
        run: npm ci
  lint:
    name: run lint
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: web/.tool-versions
      - name: npm ci
        run: npm ci
      - name: run lint
        run: npm run lint
  format:
    name: run format
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: web/.tool-versions
      - name: npm ci
        run: npm ci
      - name: run format
        run: npm run format
  type-check:
    name: run type-check
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: web/.tool-versions
      - name: npm ci
        run: npm ci
      - name: run type-check
        run: npm run type-check
  build:
    name: run build
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: web/.tool-versions
      - name: npm ci
        run: npm ci
      - name: run build
        run: npm run build
